[package]
name = "ghost"
version = "0.1.0"
authors = ["xiongbingchao <xiongbingchao@youzan.com>"]

[dependencies]
diesel = { version = "0.16.0", features = ["mysql"] }
diesel_codegen = { version = "0.16.0", features = ["mysql"] }
dotenv = "0.9.0"